### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by capaj** [Gozala/standard-flow#2]
```
success Saved 1 new dependency.
└─ standard-flow@1.0.0

> standard-flow

standard-flow: Unexpected linter output:

TypeError: Cannot read property 'value' of undefined
    at getStarToken (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/rules/generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.enterNode (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/standard-flow/node_modules/eslint/lib/eslint.js:895:36)
    at Controller.__execute (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/capaj/git_projects/tgm/tgm-frontend/node_modules/estraverse/estraverse.js:501:28)

```

**Comment by sergesemashko** [comment]
I have the same issue. @capaj, where you able to figure it out?

**Comment by matthewmueller** [comment]
seems related to async/await usage
